name: arcane_framework
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/hanskokx/arcane_framework

environment:
  sdk: ^3.5.2
  flutter: ">=1.17.0"

dependencies:
  app_tracking_transparency: ^2.0.6
  collection: ^1.18.0
  flutter:
    sdk: flutter
  logger: ^2.4.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
