name: arcane_framework
description: "Agnostic Reusable Component Architecture for New Ecosystems: a modern framework for bootstrapping new applications"
version: 1.1.2
repository: https://github.com/hanskokx/arcane_framework
issue_tracker: https://github.com/hanskokx/arcane_framework/issues

topics:
  - arcane-framework

environment:
  sdk: ^3.5.2
  flutter: ">=1.17.0"

dependencies:
  arcane_helper_utils: ^1.0.1
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_secure_storage: ^9.2.2
  result_monad: ^2.3.2

dev_dependencies:
  arcane_analysis: ^1.0.1
  flutter_test:
    sdk: flutter
